import {
  faFutbol,
  faHammer,
  faCalendarDays,
  faUtensils,
  faStethoscope,
  faHotel,
  faCar,
  faGears,
  faPaw,
  faScrewdriverWrench,
  faBullhorn,
  faEllipsis,
  faHouse,
  faGraduationCap,
  faStore,
  faPlane,
  faMoneyBillWave,
  faTruck,
  faChalkboardUser,
  faSpa,
  faBook,
  faLandmark,
} from "@fortawesome/free-solid-svg-icons";

// Datos de categorías con subcategorías para la SuperGuía
export const CATEGORIES = [
  { id: 1, nombre: "Deportes", icon: faFutbol },
  { id: 2, nombre: "Construcción", icon: faHammer },
  { id: 3, nombre: "Eventos", icon: faCalendarDays },
  { id: 4, nombre: "Comida", icon: faUtensils },
  { id: 5, nombre: "Medicina", icon: faStethoscope },
  { id: 6, nombre: "Hospedajes", icon: faHotel },
  { id: 7, nombre: "Automóvil", icon: faCar },
  { id: 8, nombre: "Maquinaria", icon: faGears },
  { id: 9, nombre: "Mascotas", icon: faPaw },
  { id: 10, nombre: "Serv. técnico", icon: faScrewdriverWrench },
  { id: 11, nombre: "Publicidad", icon: faBullhorn },
  { id: 12, nombre: "Otros", icon: faEllipsis },
  { id: 13, nombre: "Servicios al hogar", icon: faHouse },
  { id: 14, nombre: "Academias", icon: faGraduationCap },
  { id: 15, nombre: "Comercial", icon: faStore },
  { id: 16, nombre: "Turismo", icon: faPlane },
  { id: 17, nombre: "Serv. financieros", icon: faMoneyBillWave },
  { id: 18, nombre: "Transporte", icon: faTruck },
  { id: 19, nombre: "Capacitaciones", icon: faChalkboardUser },
  { id: 20, nombre: "Belleza", icon: faSpa },
  { id: 21, nombre: "Educación", icon: faBook },
  { id: 22, nombre: "Serv. municipales", icon: faLandmark },
];

// Estructura Ciudad → Comunas del Maule
export const LOCATIONS = {
  curico: {
    nombre: "Curicó",
    comunas: [
      "Curicó",
      "Teno",
      "Romeral",
      "Molina",
      "Sagrada Familia",
      "Hualañé",
      "Licantén",
      "Vichuquén",
      "Rauco",
    ],
  },
  talca: {
    nombre: "Talca",
    comunas: [
      "Talca",
      "Constitución",
      "Curepto",
      "Empedrado",
      "Maule",
      "Pelarco",
      "Pencahue",
      "Río Claro",
      "San Clemente",
      "San Rafael",
    ],
  },
  linares: {
    nombre: "Linares",
    comunas: [
      "Linares",
      "Colbún",
      "Longaví",
      "Parral",
      "Retiro",
      "San Javier",
      "Villa Alegre",
      "Yerbas Buenas",
    ],
  },
  cauquenes: {
    nombre: "Cauquenes",
    comunas: ["Cauquenes", "Chanco", "Pelluhue"],
  },
};

// Datos de ejemplo para publicaciones
export const MOCK_PUBLICATIONS = [
  {
    id: 1,
    titulo: "Campeonato Nacional Mountainbike",
    imagen: "/img/mock/pub1.jpg",
    ciudad: "Pencahue",
    categoria: "Deportes",
    fecha: "5-7 Diciembre 2025",
  },
  {
    id: 2,
    titulo: "LL Jazzer - Lanzamiento 2049",
    imagen: "/img/mock/pub2.jpg",
    ciudad: "Curicó",
    categoria: "Eventos",
    fecha: "5 Diciembre 2025",
  },
  {
    id: 3,
    titulo: "Terra Carnaval 2da Versión",
    imagen: "/img/mock/pub3.jpg",
    ciudad: "Talca",
    categoria: "Eventos",
    fecha: "6 Diciembre 2025",
  },
  {
    id: 4,
    titulo: "Ecos del Bienestar",
    imagen: "/img/mock/pub4.jpg",
    ciudad: "Teno",
    categoria: "Medicina",
    fecha: "Diciembre 2025",
  },
  {
    id: 5,
    titulo: "III Encuentro Familiar de Rugby",
    imagen: "/img/mock/pub5.jpg",
    ciudad: "Talca",
    categoria: "Deportes",
    fecha: "6 Diciembre 2025",
  },
  {
    id: 6,
    titulo: "Feria Gastronómica del Maule",
    imagen: "/img/mock/pub6.jpg",
    ciudad: "Curicó",
    categoria: "Comida",
    fecha: "10 Diciembre 2025",
  },
];
